use [MASTER]
GO

IF DB_ID('$(UMBRACO_DB_NAME)') IS NOT NULL
    set noexec on

CREATE DATABASE [$(UMBRACO_DB_NAME)]
GO

USE [$(UMBRACO_DB_NAME)]
GO  

SET ANSI_NULLS on
GO

CREATE LOGIN $(UMBRACO_DB_USER_LOGIN) WITH PASSWORD = '$(UMBRACO_DB_USER_PASSWORD)';  
GO  

CREATE USER $(UMBRACO_DB_USER_NAME) FOR LOGIN $(UMBRACO_DB_USER_LOGIN);  
GO

ALTER ROLE db_datareader ADD MEMBER $(UMBRACO_DB_USER_NAME)
GO

ALTER ROLE db_datawriter ADD MEMBER $(UMBRACO_DB_USER_NAME)
GO

ALTER ROLE db_ddladmin ADD MEMBER $(UMBRACO_DB_USER_NAME)
GO
